#ifndef DECKLINK_C_TYPES_H
#define DECKLINK_C_TYPES_H

#include "../interop/Linux/include/DeckLinkAPI.h"

typedef IDeckLinkTimecode cdecklink_timecode_t;
typedef IDeckLinkDisplayModeIterator cdecklink_display_mode_iterator_t;
typedef IDeckLinkDisplayMode cdecklink_display_mode_t;
typedef IDeckLink cdecklink_device_t;
typedef IDeckLinkConfiguration cdecklink_configuration_t;
typedef IDeckLinkEncoderConfiguration cdecklink_encoder_configuration_t;
typedef IDeckLinkDeckControlStatusCallback cdecklink_deck_control_status_callback_t;
typedef IDeckLinkDeckControl cdecklink_deck_control_t;
typedef IDeckLinkVideoOutputCallback cdecklink_video_output_callback_t;
typedef IDeckLinkInputCallback cdecklink_input_callback_t;
typedef IDeckLinkEncoderInputCallback cdecklink_encoder_input_callback_t;
typedef IDeckLinkMemoryAllocator cdecklink_memory_allocator_t;
typedef IDeckLinkAudioOutputCallback cdecklink_audio_output_callback_t;
typedef IDeckLinkIterator cdecklink_iterator_t;
typedef IDeckLinkAPIInformation cdecklink_api_information_t;
typedef IDeckLinkOutput cdecklink_output_t;
typedef IDeckLinkInput cdecklink_input_t;
typedef IDeckLinkEncoderInput cdecklink_encoder_input_t;
typedef IDeckLinkVideoFrame cdecklink_video_frame_t;
typedef IDeckLinkMutableVideoFrame cdecklink_mutable_video_frame_t;
typedef IDeckLinkVideoFrame3DExtensions cdecklink_video_frame3_d_extensions_t;
typedef IDeckLinkVideoFrameMetadataExtensions cdecklink_video_frame_metadata_extensions_t;
typedef IDeckLinkVideoInputFrame cdecklink_video_input_frame_t;
typedef IDeckLinkVideoFrameAncillary cdecklink_video_frame_ancillary_t;
typedef IDeckLinkEncoderPacket cdecklink_encoder_packet_t;
typedef IDeckLinkEncoderVideoPacket cdecklink_encoder_video_packet_t;
typedef IDeckLinkEncoderAudioPacket cdecklink_encoder_audio_packet_t;
typedef IDeckLinkH265NALPacket cdecklink_h265nal_packet_t;
typedef IDeckLinkAudioInputPacket cdecklink_audio_input_packet_t;
typedef IDeckLinkScreenPreviewCallback cdecklink_screen_preview_callback_t;
typedef IDeckLinkGLScreenPreviewHelper cdecklink_gl_screen_preview_helper_t;
typedef IDeckLinkNotificationCallback cdecklink_notification_callback_t;
typedef IDeckLinkNotification cdecklink_notification_t;
typedef IDeckLinkAttributes cdecklink_attributes_t;
typedef IDeckLinkStatus cdecklink_status_t;
typedef IDeckLinkKeyer cdecklink_keyer_t;
typedef IDeckLinkVideoConversion cdecklink_video_conversion_t;
typedef IDeckLinkDeviceNotificationCallback cdecklink_device_notification_callback_t;
typedef IDeckLinkDiscovery cdecklink_discovery_t;

#endif //DECKLINK_C_TYPES_H
